ALTER TABLE "CandidateProfile"
ADD COLUMN "email" TEXT NOT NULL DEFAULT '',
ADD COLUMN "phone" TEXT NOT NULL DEFAULT '',
ADD COLUMN "portfolioUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN "githubUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN "summary" TEXT NOT NULL DEFAULT '';
CREATE TABLE "Resume" (
 "id" TEXT NOT NULL PRIMARY KEY,
 "candidateId" TEXT NOT NULL UNIQUE REFERENCES "CandidateProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE,
 "fileName" TEXT NOT NULL,
 "mimeType" TEXT NOT NULL DEFAULT 'application/pdf',
 "sha256" TEXT NOT NULL,
 "sizeBytes" INTEGER NOT NULL,
 "content" BYTEA NOT NULL,
 "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updatedAt" TIMESTAMP(3) NOT NULL
);

ALTER TABLE "CandidateProfile" ALTER COLUMN "remotePreference" DROP NOT NULL;
